import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path_provider/path_provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'package:moonbase_skeleton/app.dart';
import 'package:moonbase_skeleton/firebase_options.dart';

import 'package:moonbase_skeleton/features/profile/data/repositories/profile_repository_impl.dart';
import 'package:moonbase_skeleton/features/profile/presentation/providers/profile_providers.dart' as profile_providers;

import 'package:moonbase_skeleton/features/auth/data/repositories/auth_repository_impl.dart';
import 'package:moonbase_skeleton/features/auth/presentation/providers/auth_providers.dart';
import 'package:moonbase_skeleton/features/auth/data/datasources/auth_local_data_source_impl.dart';
import 'package:moonbase_skeleton/features/auth/data/datasources/firebase_auth_remote_data_source.dart';

import 'package:moonbase_skeleton/features/chat/data/datasources/chat_shared_prefs_data_source.dart';
import 'package:moonbase_skeleton/features/chat/data/repositories/chat_repository_impl.dart';
import 'package:moonbase_skeleton/features/chat/presentation/providers/chat_providers.dart';

import 'package:moonbase_skeleton/features/bases/data/datasources/base_shared_prefs_data_source.dart';
import 'package:moonbase_skeleton/features/bases/data/repositories/base_repository_impl.dart';
import 'package:moonbase_skeleton/features/bases/presentation/providers/base_providers.dart';

import 'package:moonbase_skeleton/features/media/data/datasources/image_picker_media_picker.dart';
import 'package:moonbase_skeleton/features/media/data/datasources/local_file_media_storage.dart';
import 'package:moonbase_skeleton/features/media/presentation/providers/media_providers.dart';

import 'package:moonbase_skeleton/core/di/providers.dart' show sharedPrefsProvider;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Phase 4 foundation: Firebase must be initialized before any Firebase
  // plugin (Auth/Firestore/Storage) is touched. Options are generated by
  // `flutterfire configure` into lib/firebase_options.dart.
  try {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  final appName = Firebase.app().name;
  debugPrint('🚀 FIREBASE SUCCESS: Connected to app [$appName]');
  } catch (e) {
    debugPrint ('❌ FIREBASE ERROR: Initialization failed: $e');
  }

  final prefs = await SharedPreferences.getInstance();

  // Phase 3 foundation: resolve the app documents directory once at startup
  // so the local media root (`<docsDir>/media/<baseId>/<uuid>.<ext>`) is
  // available to LocalFileMediaStorage. See docs/PHASE3_DOD_ACTION_LIST.md
  // §0.3.5.
  final docsDir = await getApplicationDocumentsDirectory();
  final mediaStorage = LocalFileMediaStorage(docsDir);
  final mediaPicker = ImagePickerMediaPicker(storage: mediaStorage);

  final overrides = <Override>[
    sharedPrefsProvider.overrideWithValue(prefs),

    profile_providers.profileRepositoryProvider.overrideWithValue(ProfileRepositoryImpl(prefs)),

    authRepositoryProvider.overrideWithValue(
      AuthRepositoryImpl(
        local: AuthLocalDataSourceImpl(prefs),
        remote: FirebaseAuthRemoteDataSource(),
      ),
    ),

    chatRepositoryProvider.overrideWithValue(
      ChatRepositoryImpl(local: ChatSharedPrefsDataSource(prefs)),
    ),

    baseRepositoryProvider.overrideWithValue(
      BaseRepositoryImpl(local: BaseSharedPrefsDataSource(prefs)),
    ),

    // Phase 3 media foundation. The only file that has to change when Phase 4
    // cloud storage lands is this one (swap LocalFileMediaStorage for the
    // cloud impl; everything downstream is wired through the ports).
    mediaStorageProvider.overrideWithValue(mediaStorage),
    mediaPickerProvider.overrideWithValue(mediaPicker),
  ];

  runApp(ProviderScope(overrides: overrides, child: const App()));
}

